### ISSUE TITLE
Support for RPi PicoW?

### ISSUE THREAD

**Issue by DeeJay** [MrYsLab/telemetrix-rpi-pico#12]
Support for RPi PicoW?

Can you say anything about the new PicoW and compatibility with the variants of "TMX4Pico" .uf2 firmwares?

Not the wireless networking, but the handling of the on-board LED. I understand there has been some change to the way the LED is connected and driven as distinct from the original Pico.

There may be some overlap with #11

**Comment by MrYsLab** [comment]
It will be a few weeks before the PicoW arrives here in the U.S., and it is not clear how easy it will be to get one, but it is one my to-do list. 

It is my understanding that, except for the Board LED, everything else should be the same.

There is one main problem I will need to solve to support the WiFI chip. The .uf2 needs to contain the user's SSID and Password to connect to a router. This will mean that the user will need to edit a file to add their SSID and Password. The complication is the compilation environment the user will need to establish.

Currently, I use the JetBrains CLion IDE to develop the uf2 code,  but I do not expect users to pay for a tool to support my adding WiFi support. 

Perhaps the Arduino Core for the RP2040 will be expanded for WiFi support. If that is the case, I will probably rewrite the uf2 based on that library. It is a simple matter of adding the SSID and Password to a file and recompiling and uploading the "sketch" using the Arduino IDE.

Since it is free, I will also be looking at creating the RP2040 C SDK code using the MicroSoft VSCode IDE. I seem to remember that it is not that easy to set up, but that was when the Pico was first released, so perhaps things have improved.  

Sounds like I have some fun ahead of me ;-).

**Comment by DeeJay** [comment]
{Please tell me to stop if I am being annoying... }

> There is one main problem I will need to solve to support the WiFI chip. The .uf2 needs to contain the user's SSID and Password to connect to a router. This will mean that the user will need to edit a file to add their SSID and Password. The complication is the compilation environment the user will need to establish.

Is that necessary?

By comparison with the uPython implementation of the network.WLAN() module, the user passes in ssid and psk as as arguments to a connect() method. They aren't compiled in to the .uf2 or a module.

My thinking is that uPython is essential a (complex) .uf2 firmware implemented in C. Just like the Telemetrix4pico daemon?

It looks as though the telemetrix-rpi-pico: _send_command() function can send an arbitrary number of bytes. So couldn't the user configure ssid and psk for the connection from a python function in telemetrix-rpi-pico? (With corresponding support in the telemetrix4pico daemon of course.)

**Comment by MrYsLab** [comment]
@DeeJay 

Not annoying at all. 

I think uPython assumes that the REPL is available through a serial link, so the connection command would come via the REPL. If the connection is part of the Python script, then the SSID and Password must be known beforehand as part of the source code. I would love to do the Pico side in uPython, but unfortunately, uPython is just too slow for this application.

The philosophy of WiFi and Bluetooth flavors of Telemetirx is that a serial link is not required to use the library. For WiFi, this would mean that the SSID and Password must be known to automatically establish a connection to the router before the Python side is involved. The reasoning here is twofold. 
1. Using a serial link is impractical or impossible if the device is battery-powered and remote.
2. If the router should go down, one would need to use a serial link to reestablish a connection to the router.

The Arduino Core for the Pico has[ an issue](https://github.com/earlephilhower/arduino-pico/issues/666) against it to add WiFi support. Assuming Earle, the library's owner, can add WiFi support, this would be my preferred way of solving support for WiFi. It would mean all new code needs to be written to run on the Pico but would make it much easier for the user community to insert the SSID and Password into the source code, compile, and upload to the Pico. 

When I get a chance, I will revisit building Pico C++ SDK code using Visual Studio. In the past, getting the environment up and running was painful and complicated. Perhaps this has changed over time. By the way, the only reason I selected to use the Pico SDK for the current library version was that Earle's library was not yet published when I did my initial development.

Also, I already have a [WiFi version](https://github.com/MrYsLab/Telemetrix4Connect2040) available for the [Arduino Nano RP2040 Connect.](https://store-usa.arduino.cc/products/arduino-nano-rp2040-connect-with-headers?selectedStore=us). So it should be relatively easy to get it ported to the Pico.

Please feel free to continue making suggestions or to ask questions.

**Comment by MrYsLab** [comment]
@DeeJay, I finally acquired a Pico W. I have a version of [Telemetrix for the Pico W](https://github.com/MrYsLab/telemetrix-rpi-pico-w) that I am getting ready to release. I need to create the documentation, and hopefully, this will be complete in about a week or so.
The examples are all working for both the threaded and asyncio Python APIs.

**Comment by MrYsLab** [comment]
@DeeJay I just published telemetrix for the RPI Pico W. The user's guide can be found [here](https://mryslab.github.io/telemetrix-rpi-pico-w/).

**Comment by DeeJay** [comment]
Thanks. I will try to find time to take a look. It will be a good reason to explore the Arduino IDE V2.0

**Comment by MrYsLab** [comment]
Version 1.18.x also will work. The one annoying thing about 2.0 with the Pico is that it disconnects the serial port after you upload. Not a major problem, but when changing the sketch code during development, you need to constantly reset the port for each upload.
