### ISSUE TITLE
Help Please  Can this be used to control a usb cell modem? 

### ISSUE THREAD

**Issue by Snakn1** [MrYsLab/telemetrix-rpi-pico#14]
Hello I am thinking of using this as a remote water detector.  There is no WIFI and I want to open a HTML page with my information.  I know how to make the cable (micro usb to female usb 2.0) but that is where I stumble or if the Pico has the ram to run the wvdial program.

**Comment by MrYsLab** [comment]
I believe wvdial requires an operating system such as Linux. Since the Pico does not have an operating system and the PPP protocol is somewhat complex, It will be tough to accomplish what you are trying to do with the Pico. 
A better option might be to use something like a Raspberry Pi Zero. In that case, you would not use Telemetrix but write the program using a library such as [pigpio](https://abyz.me.uk/rpi/pigpio/) to control the GPIO pins of the Zero, and you would [install wvdial](https://www.thefanclub.co.za/how-to/how-setup-usb-3g-modem-raspberry-pi-using-usbmodeswitch-and-wvdial) on the board.

**Comment by Snakn1** [comment]
thank you for this info. I am just starting to play with one and was going to use it due to the power needs of the larger pi. but I did not think about a pi zero. I will look in to that.

**Comment by MrYsLab** [comment]
I am closing this since it is not an issue with this repository. However, please feel free to post any additional comments or questions here, and I will see them.
